### ISSUE TITLE
Regular Lists and Dictionaries

### ISSUE THREAD

**Issue by brmassa** [bodong1987/Avalonia.PropertyGrid#1]
Congrats! Great library.

It's still missing the ability to display regular Lists and Dictionaries, besides BindingList.

**Comment by bodong1987** [comment]
Because I need to use some internal change notification events of BindingList to implement some functions, the standard List and Dictionary may not have these notifications.
for example: 
event ListChangedEventHandler ListChanged;

**Comment by appel1** [comment]
What about ObservableCollection?
