### ISSUE TITLE
FloatPrecisionAttribute

### ISSUE THREAD

**Issue by NOoBODDY** [bodong1987/Avalonia.PropertyGrid#17]
Why the second constructor of FloatPrecisionAttribute has Decimal parameter? 
CLR does'not allow use Decimal in attributes. So when I tried use FloatPrecisionAttribute, i have an error

**Comment by bodong1987** [comment]
> Why the second constructor of FloatPrecisionAttribute has Decimal parameter? CLR does'not allow use Decimal in attributes. So when I tried use FloatPrecisionAttribute, i have an error

you can create a child class of FloatPrecisionAttribute, and convert your type to Decimal by yourself in your constructor.
I will change this later.

**Comment by bodong1987** [comment]
> Why the second constructor of FloatPrecisionAttribute has Decimal parameter? CLR does'not allow use Decimal in attributes. So when I tried use FloatPrecisionAttribute, i have an error

I use Decimal because Avalonia's control use Decimal.

**Comment by NOoBODDY** [comment]
Thank you for your answer
