### ISSUE TITLE
Property's UI doesnt update when making changes to property in code

### ISSUE THREAD

**Issue by artizzq** [bodong1987/Avalonia.PropertyGrid#18]
I have one problem. For example, when I change property (e. g., DateTime) manually, by hand, and want to correct its value in code, I notice that visually nothing changes in control according to in-code changes. It shows not corrected value but the one I chose using picker and I notice corresponding changes only in code (variables).
What possible reasons could be for it? I tried to define object as ReactiveObject and used "this.RaiseAndSetIfChanged" in set but no avail.

![image](https://github.com/bodong1987/Avalonia.PropertyGrid/assets/56273839/ecb9196a-bf9c-499b-8c1b-23c4937d529f)
![image](https://github.com/bodong1987/Avalonia.PropertyGrid/assets/56273839/066520f9-d31f-4bc3-b2cb-6aeda961293c)
![image](https://github.com/bodong1987/Avalonia.PropertyGrid/assets/56273839/97a750b6-cc6c-4523-85bb-291d73630ff7)

Is there any specific UI refresh command I missed?

**Comment by bodong1987** [comment]
> I have one problem. For example, when I change property (e. g., DateTime) manually, by hand, and want to correct its value in code, I notice that visually nothing changes in control according to in-code changes. It shows not corrected value but the one I chose using picker and I notice corresponding changes only in code (variables). What possible reasons could be for it? I tried to define object as ReactiveObject and used "this.RaiseAndSetIfChanged" in set but no avail.
> 
> 我有一个问题。例如，当我手动更改属性(例如，DateTime)并希望在代码中更正其值时，我注意到根据代码内的更改，控制在视觉上没有任何变化。它没有显示更正的值，而是我使用 picker 选择的值，我只注意到代码(变量)中的相应变化。有什么可能的原因吗？我尝试将 object 定义为 ReactiveObject，并使用“ this。RaiseAndSetIfChanged”，但无效。
> 
> ![image](https://private-user-images.githubusercontent.com/56273839/290488252-ecb9196a-bf9c-499b-8c1b-23c4937d529f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjE4NzEsIm5iZiI6MTcwMjg2MTU3MSwicGF0aCI6Ii81NjI3MzgzOS8yOTA0ODgyNTItZWNiOTE5NmEtYmY5Yy00OTliLThjMWItMjNjNDkzN2Q1MjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAxMDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNDY4NzRiZWYzNWQ2ZWYxZjM4ZWZlZGJmNWEwOTM5M2IxMTM4MzA3ZmYyYTAyZjZlNjVkNDgyNDJjZjBjZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yxmOwzMXyHB8_XQvgEK_tJTMoDhHqOvgq8W5At35YEM) ![image](https://private-user-images.githubusercontent.com/56273839/290488383-066520f9-d31f-4bc3-b2cb-6aeda961293c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjE4NzEsIm5iZiI6MTcwMjg2MTU3MSwicGF0aCI6Ii81NjI3MzgzOS8yOTA0ODgzODMtMDY2NTIwZjktZDMxZi00YmMzLWIyY2ItNmFlZGE5NjEyOTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAxMDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjODZlNmRjY2VkOWI4OTQ4NDJhZTJjMGViMDYxNWE3MzU1NjMzMDc2MDhiNzFlYjI5Zjk3N2E0MWI2Y2Q0MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DrxLCqVHFPL-gztRrTLVCFZFWHn5RP3I5QYHuIE6rXo) ![image](https://private-user-images.githubusercontent.com/56273839/290488596-97a750b6-cc6c-4523-85bb-291d73630ff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjE4NzEsIm5iZiI6MTcwMjg2MTU3MSwicGF0aCI6Ii81NjI3MzgzOS8yOTA0ODg1OTYtOTdhNzUwYjYtY2M2Yy00NTIzLTg1YmItMjkxZDczNjMwZmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAxMDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZjI2YWY2YzU3ODU3OTc2ODU5YjNiZDk3MzQ0ZDZiMzViOTQzOTdlMmY2MTIyMTQ0M2IxMDE2Yzc5OTVmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eujGgl_uIsNnu-4GjPel0d_UHCv4SN0ZoiMxkRy0JZk)
> 
> Is there any specific UI refresh command I missed?
> 
> 是否有我遗漏的特定 UI 刷新命令？

There is no interface to refresh the UI, everything is automatic. In theory, as long as the System.ComponentModel.INotifyPropertyChanged interface is implemented. There seems to be no problem with your operation. If the UI is not refreshed, there must be some special circumstances. Without the source code, it's difficult for me to determine the cause. If possible, it is recommended that you create a simple Avalonia Demo Project, then extract this small piece of code and add it, and then try to see if you can reproduce the problem. You can also send me this small DemoProject.

Or you can try to debug the source code directly. The relevant code is located at: DateTimeCellEditFactory.cs/HandlePropertyChanged

In addition, you can also confirm whether the RaiseAndSetIfChanged you called really takes effect, such as monitoring the PropertyChanged event of your own object.

**Comment by bodong1987** [comment]
[AvaloniaApplication23.zip](https://github.com/bodong1987/Avalonia.PropertyGrid/files/13824846/AvaloniaApplication23.zip)
check this demo.
