### ISSUE TITLE
Does using the [TypeConverter(typeof(ExpandableObjectConverter))] attribute support custom layout for expanding class properties?

### ISSUE THREAD

**Issue by qian-o** [bodong1987/Avalonia.PropertyGrid#25]
Hi, I've noticed that when using this attribute to expand properties, they are always displayed on the right-hand side. This display effect is not very optimal when the property class has multiple levels.
![image](https://github.com/bodong1987/Avalonia.PropertyGrid/assets/84434846/375569eb-23aa-43c1-b29d-e24cf0dcd1a1)

Is it possible to change it to resemble tree nodes, displaying a title node, and upon clicking, expanding a group of property lists below? Similar to the diagram below.
![image](https://github.com/bodong1987/Avalonia.PropertyGrid/assets/84434846/8d6aedbc-07b3-438c-b3e8-9b5d8c6b256e)

**Comment by bodong1987** [comment]
> Hi, I've noticed that when using this attribute to expand properties, they are always displayed on the right-hand side. This display effect is not very optimal when the property class has multiple levels. ![image](https://private-user-images.githubusercontent.com/84434846/320767216-375569eb-23aa-43c1-b29d-e24cf0dcd1a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjEzMTcsIm5iZiI6MTcxMjgyMTAxNywicGF0aCI6Ii84NDQzNDg0Ni8zMjA3NjcyMTYtMzc1NTY5ZWItMjNhYS00M2MxLWIyOWQtZTI0Y2YwZGNkMWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA3MzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiODhmZjgxMTBjMWZhMjQ0M2U3NjE2NGI3M2Q5MDU3OTM4Y2UyNzUwNGIyNzIxMGQwYTNkZTdmOWVmNzZkMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eVy12G1dOjiGUpoMblZxZcWKEsHizKXO3cyPW-QisWA)
> 
> Is it possible to change it to resemble tree nodes, displaying a title node, and upon clicking, expanding a group of property lists below? Similar to the diagram below. ![image](https://private-user-images.githubusercontent.com/84434846/320766951-8d6aedbc-07b3-438c-b3e8-9b5d8c6b256e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjEzMTcsIm5iZiI6MTcxMjgyMTAxNywicGF0aCI6Ii84NDQzNDg0Ni8zMjA3NjY5NTEtOGQ2YWVkYmMtMDdiMy00MzhjLWIzZTgtOWI1ZDhjNmIyNTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA3MzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NDJiMDZmMjUwNzdhZjc3MGYxODcwMmIzMDljZTIzM2ZkOGE3YTAwY2Q2OTNiMTZmNzcxNmE0Zjg1ZDQ3MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tLUdrtvHsL9MEtEAo_QUCWTIsP-PVMmEA059ZuCsbmY)

目前暂时无法支持该风格。现在的做法对于子对象来说，是使用的一个嵌套的PropertyGrid来实现的。如果要改成树形控件的话，那就改动太大了，不亚于重新创建一个控件了。

**Comment by qian-o** [comment]
好吧，感谢您的答疑。
