### ISSUE TITLE
Bug with System.ComponentModel.DataAnnotations.RangeAttribute

### ISSUE THREAD

**Issue by tsctsc6** [bodong1987/Avalonia.PropertyGrid#38]
When using RangeAttribute, if max value greater than or equal to 7.9296875E+28, the PropertyGrid show not thing.
For example, if one of the properties of my model class
```
[Range(0, 7.9296875E+28, ErrorMessage = "单价大于0")]
public double UnitPrice { get; set; } = 0;
```
the PropertyGrid show not thing.

Avalonia.PropertyGrid version: 11.1.1.1
Avalonia version: 11.1.1

**Comment by bodong1987** [comment]
avalonia内部使用的数值是Decimal，对于这种类型来说，7.9296875E+28太大了。

**Comment by tsctsc6** [comment]
I see.
