### ISSUE TITLE
[Bug] BoundedList with custom type doesn't work properly

### ISSUE THREAD

**Issue by Elscrux** [bodong1987/Avalonia.PropertyGrid#7]
I really like what you've done, although I've stumbled over some issues trying it out.
Annotating a custom class with `[TypeConverter(typeof(ExpandableObjectConverter))]` doesn't show the properties of the class, just the `ToString()` value. Adding a custom `AbstractCellEditFactory` that can handle the custom class seems to be a workaround for this, but it would be nice to have a native way to support these kinds of lists.

```cs
[TypeConverter(typeof(ExpandableObjectConverter))]
public class Vector3 : MiniReactiveObject { ... }
```

```cs
public BindingList<Vector3> PositionsList { get; set; } = new()
```

This shows all properties of `Vector3` as expected:
```cs
public Vector3 Position { get; set; }
```

**Comment by bodong1987** [comment]
Thank you for your feedback, I have fixed this issue in the latest rc version.
